# -*- coding: utf-8 -*-
"""Lab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m9KiXv9ltBJ6ITPuWD2UYelKyRn-gJXt

Задание 1
"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        self.prev = None



class LinkedListDeque:
    def __init__(self):
        self.front = None
        self.rear = None
        self.size = 0

    def add_front(self, item):
        new_node = Node(item)
        if self.is_empty():
            self.front = self.rear = new_node
        else:
            new_node.next = self.front
            self.front.prev = new_node
            self.front = new_node
        self.size += 1

    def add_rear(self, item):
            new_node = Node(item)
            if self.is_empty():
                self.front = self.rear = new_node
            else:
                new_node.prev = self.rear
                self.rear.next = new_node
                self.rear = new_node
            self.size += 1


    def remove_front(self):
        if self.is_empty():
            raise IndexError("Deque is empty")
        item = self.front.data
        self.front = self.front.next
        if self.front:
            self.front.prev = None
        else:
            self.rear = None
        self.size -= 1
        return item

    def remove_rear(self):
        if self.is_empty():
            raise IndexError("Deque is empty")
        item = self.rear.data
        self.rear = self.rear.prev
        if self.rear:
            self.rear.next = None
        else:
            self.front = None
        self.size -= 1
        return item

    def is_empty(self):
        return self.size == 0

    def is_polindrom(self):
        if self.is_empty():
            return True
        size = self.size
        step_cnt = size//2
        scur = self.front
        ncur = self.rear
        for _ in range(step_cnt):
            if scur.data != ncur.data:
                return False
            scur = scur.next
            ncur = ncur.prev
        return True

    def out(self):
        cur = self.front
        for i in range(self.size):
            print(cur.data, end = '')
            cur = cur.next
        print()
        return



dek = LinkedListDeque()

a = 'ABOBA'
for i in a:
    dek.add_front(i)

print(dek.size)
dek.out()
print(dek.is_polindrom())

"""Задание 2"""

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None



class LinkedStack:
    def __init__(self):
        self.top = None

    def push(self, item):
        new_node = Node(item)
        new_node.next = self.top
        self.top = new_node

    def pop(self):
        if self.is_empty():
            raise IndexError("Pop from empty stack")
        item = self.top.data
        self.top = self.top.next
        return item

    def is_empty(self):
        return self.top == None



def CanExit(entering, stack):
    ent = entering
    posled = [i+1 for i in range(len(ent))]
    for car in ent:
        if car in posled:
            for i in range(len(posled)):
                ncar = posled[i]
                stack.push(ncar)
                posled[i] = None
                if ncar == car:
                    break
        p = stack.pop()
        if p != car:
            return False
    return True



entering = [3,2,1,4,5]
stk = LinkedStack()

print(CanExit(entering, stk))

"""Задание 3"""

capacity = 10
nstacks = 3
stacks = [[1,2], [2,5,7], [7,8]]
mas1 = [None for i in range(capacity)]
mas2 = [None for i in range(capacity)]

for i in range(len(stacks)):
    if stacks[i]:
        mas1[i] = (stacks[i][0])
    else:
        mas1[i] = None
    mas2[i] = (i+1)

def Add_to_stack(data, stack_num):
    if mas2.count(stack_num) == 1 and mas1[stack_num-1] == None:
        mas1[stack_num-1] = data
    idx = None
    for i in range(nstacks, capacity):
        if mas1[i] == None:
            idx = i
            break
    mas1[idx] = data
    mas2[idx] = stack_num
    return

def Del_from_stack(stack_num):
    idx = None
    for i in range(capacity-1, -1, -1):
        if mas2[i] == stack_num:
            idx = i
            break
    mas1[idx] = None
    if mas2.count(stack_num) != 1:
        mas2[idx] = None
    return

def print_stacks(mas1, mas2, nstacks):
    for stack_num in range(1, nstacks + 1):
        print(f"Stack {stack_num}:", end=" ")

        elements = []
        for i in range(capacity):
            if mas2[i] == stack_num and mas1[i] is not None:
                elements.append(mas1[i])

        if elements:
            print(" -> ".join(str(elem) for elem in reversed(elements)), end="")

        print(" -> None")

for i in range(nstacks):
    if len(stacks[i]) > 1:
        for j in range(1, len(stacks[i])):
            Add_to_stack(stacks[i][j], i+1)

Add_to_stack(99, 1)
Add_to_stack(5678, 3)
Add_to_stack(7856, 2)

print("После добавления элементов:")
print(mas1, mas2, sep='\n')
print()

Del_from_stack(3)

print("После удаления элемента из стека 3:")
print(mas1, mas2, sep='\n')
print()

print("Красивый вывод стеков:")
print_stacks(mas1, mas2, nstacks)