# -*- coding: utf-8 -*-
"""Lab8_trees.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e78ooP7_4sewSr-sps_xOAQrPOSAapzl

Задание 1
"""

from typing import Optional, Any



class Node:
    def __init__( self, value ):
        self.value = value
        self.left = None
        self.right = None


def depth( root: Optional[Node], value: Any, current_depth = 0 ) -> int:
    if root is None:
        return -1

    if root.value == value:
        return current_depth

    left_depth = depth( root.left, value, current_depth + 1 )
    if left_depth != -1:
        return left_depth

    return depth( root.right, value, current_depth + 1 )


def lca( root: Optional[Node], a: Any, b: Any ) -> Optional[Any]:
    if root is None:
        return None

    if root.value == a or root.value == b:
        return root.value

    left = lca( root.left, a, b )
    right = lca( root.right, a, b )

    if left and right:
        return root.value

    return left or right


def mirror( root: Optional[Node] ) -> None:
    if root is None:
        return

    mirror( root.left )
    mirror( root.right )

    root.left, root.right = root.right, root.left


def dist( root: Node, a: Any, b: Any) -> int:

    LCA = lca( root, a, b )

    return depth(root, a) + depth(root, b) - 2*depth(root, LCA)


def print_tree(node, prefix="", is_left=True):

    if node is not None:
        print_tree(node.right, prefix + ("│   " if is_left else "    "), False)
        print(prefix + ("└── " if is_left else "┌── ") + str(node.value))
        print_tree(node.left, prefix + ("    " if is_left else "│   "), True)



root = Node(1)
root.left = Node(2)
root.left.left = Node(4)
root.left.right = Node(5)
root.right = Node(3)
root.right.left = Node(6)
root.right.right = Node(7)

print_tree(root)

print()
print(lca(root, 4, 5))
print(lca(root, 2, 5))
print(lca(root, 4, 3))


mirror(root)
print()
print_tree(root)

print(dist(root, 4, 7))

"""Задание 2"""

import time
import random
import sys
import heapq
from typing import List, Callable, Tuple
from functools import wraps

sys.setrecursionlimit(10**6)



def timer_decorator(func_name: str = None):

    def decorator(func: Callable) -> Callable:

        @wraps(func)
        def wrapper(*args, **kwargs):

            start = time.perf_counter()
            result = func(*args, **kwargs)
            end = time.perf_counter()
            elapsed_ms = (end - start) * 1000
            name = func_name if func_name else func.__name__

            return result, elapsed_ms, name

        return wrapper

    return decorator



def merge(left: List[int], right: List[int]) -> List[int]:

    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])

    return result


@timer_decorator("Слияние (ст.)")
def merge_sort_standard(arr: List[int]) -> List[int]:

    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = merge_sort_standard(arr[:mid])[0]
    right = merge_sort_standard(arr[mid:])[0]

    return merge(left, right)


@timer_decorator("Быстрая (ст.)")
def quick_sort_standard(arr: List[int]) -> List[int]:

    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quick_sort_standard(left)[0] + middle + quick_sort_standard(right)[0]


@timer_decorator("Python sorted()")
def builtin_sort(arr: List[int]) -> List[int]:
    return sorted(arr)



def merge_optimized(arr: List[int], temp: List[int], left: int, mid: int, right: int) -> None:

    i, j, k = left, mid + 1, left
    while i <= mid and j <= right:
        if arr[i] <= arr[j]:
            temp[k] = arr[i]
            i += 1
        else:
            temp[k] = arr[j]
            j += 1
        k += 1
    while i <= mid:
        temp[k] = arr[i]
        i += 1
        k += 1
    while j <= right:
        temp[k] = arr[j]
        j += 1
        k += 1
    for i in range(left, right + 1):
        arr[i] = temp[i]


def merge_sort_optimized_internal(arr: List[int], temp: List[int], left: int, right: int) -> None:

    if left >= right:
        return
    mid = (left + right) // 2
    merge_sort_optimized_internal(arr, temp, left, mid)
    merge_sort_optimized_internal(arr, temp, mid + 1, right)
    merge_optimized(arr, temp, left, mid, right)


@timer_decorator("Слияние (опт.)")
def merge_sort_optimized(arr: List[int]) -> List[int]:

    arr_copy = arr.copy()
    temp = [0] * len(arr_copy)
    merge_sort_optimized_internal(arr_copy, temp, 0, len(arr_copy) - 1)
    return arr_copy


def quick_sort_optimized_internal(arr: List[int], low: int, high: int) -> None:

    if low >= high:
        return

    if high - low < 20:
        insertion_sort(arr, low, high)
        return

    mid = (low + high) // 2
    if arr[low] > arr[mid]:
        arr[low], arr[mid] = arr[mid], arr[low]
    if arr[low] > arr[high]:
        arr[low], arr[high] = arr[high], arr[low]
    if arr[mid] > arr[high]:
        arr[mid], arr[high] = arr[high], arr[mid]

    pivot = arr[mid]
    arr[mid], arr[high] = arr[high], arr[mid]

    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    pivot_index = i + 1

    quick_sort_optimized_internal(arr, low, pivot_index - 1)
    quick_sort_optimized_internal(arr, pivot_index + 1, high)


def insertion_sort(arr: List[int], low: int, high: int) -> None:

    for i in range(low + 1, high + 1):
        key = arr[i]
        j = i - 1
        while j >= low and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key


@timer_decorator("Быстрая (опт.)")
def quick_sort_optimized(arr: List[int]) -> List[int]:

    arr_copy = arr.copy()
    quick_sort_optimized_internal(arr_copy, 0, len(arr_copy) - 1)

    return arr_copy


@timer_decorator("Кучей")
def heap_sort(arr):
    heapq.heapify(arr)
    result = []
    while arr:
        result.append(heapq.heappop(arr))
    return result



def run_tests(sizes: List[int]) -> None:

    sort_functions = [
        merge_sort_standard,
        quick_sort_standard,
        builtin_sort,
        merge_sort_optimized,
        quick_sort_optimized,
        heap_sort
    ]

    for size in sizes:
        print(f"\n{'='*60}")
        print(f"Размер массива: {size}")
        print('-' * 60)
        print(f"{'Метод':<35} | {'Время (мс)':>10}")
        print('-' * 60)

        original_arr = [random.randint(0, size) for _ in range(size)]

        results = {}
        for sort_func in sort_functions:
            result, elapsed_ms, name = sort_func(original_arr.copy())
            results[name] = elapsed_ms
            print(f"{name:<35} | {elapsed_ms:>10.2f}")

        print('-' * 60)

        if "Слияние (стандарт)" in results and "Слияние (оптимизир.)" in results:
            speedup = results["Слияние (стандарт)"] / results["Слияние (оптимизир.)"]
            print(f"Слияние (оптимизир.) быстрее стандартной в {speedup:.2f}x")

        if "Быстрая (стандарт)" in results and "Быстрая (оптимизир.)" in results:
            speedup = results["Быстрая (стандарт)"] / results["Быстрая (оптимизир.)"]
            print(f"Быстрая (оптимизир.) быстрее стандартной в {speedup:.2f}x")

        if "Слияние (оптимизир.)" in results and "Быстрая (оптимизир.)" in results:
            if results["Быстрая (оптимизир.)"] < results["Слияние (оптимизир.)"]:
                diff = results["Слияние (оптимизир.)"] - results["Быстрая (оптимизир.)"]
                print(f"Быстрая (оптимизир.) быстрее Слияния (оптимизир.) на {diff:.2f} мс")
            else:
                diff = results["Быстрая (оптимизир.)"] - results["Слияние (оптимизир.)"]
                print(f"Слияние (оптимизир.) быстрее Быстрой (оптимизир.) на {diff:.2f} мс")

        if "Python sorted()" in results and "Слияние (стандарт)" in results:
            speedup = results["Слияние (стандарт)"] / results["Python sorted()"]
            print(f"Python sorted() быстрее стандартного слияния в {speedup:.1f}x")


    print("\n" + "=" * 60)



def main():
    print("="*60)
    print(" " * 15 + "Сравнение алгоритмов сортировки")
    print("="*60)

    sizes = [10**3, 10**4, 10**5, 10**6]
    run_tests(sizes)



if __name__ == "__main__":
    main()

"""Задание 3"""

import heapq



def merge_sorted_arrs( arrs: list ) -> list:

    res = []
    heap = []

    for i, arr in enumerate( arrs ):
        if arr:
            heapq.heappush( heap, (arr[0], i, 0) )

    while heap:
        val, arr_idx, el_idx = heapq.heappop(heap)
        res.append( val )

        if el_idx + 1 < len( arrs[arr_idx]):
            next_val = arrs[arr_idx][el_idx + 1]
            heapq.heappush( heap, (next_val, arr_idx, el_idx + 1) )

    return res



arrs = [
    [1,2,3,4],
    [2,4,6,8],
    [3,5,7,9]
]

print(merge_sorted_arrs(arrs))