# -*- coding: utf-8 -*-
"""Lab6_sortings.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Fj4Zfbp4XX4WQRtOW_dKuOjbp_JUQZt

Задание 1 (Бинарный поиск: циклом)
"""

def cicle_bin_search( arr: list, num: int ) -> int:

    left_ind, right_ind = 0, len( arr )

    while left_ind <= right_ind:
        mid = ( left_ind + right_ind ) // 2
        if arr[ mid ] < num:
            left_ind = mid
        elif arr[ mid ] > num:
            right_ind = mid
        else:
            return mid

    return -1



if __name__ == '__main__':
    arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    x =  4
    idx = cicle_bin_search(arr, x)
    print( f'Индекс: { idx }, элемент: { x }' )

"""Задание 1 (Бинарный поиск: рекурсией)"""

def recursion_bin_search( arr: list, num: int) -> int:

    left_ind, right_ind = 0, len(arr) - 1

    if left_ind <= right_ind:
        mid = ( left_ind + right_ind ) // 2
        if arr[ mid ] < num:
            recursion_bin_search( arr[ mid + 1 : right_ind ], num )
        elif arr[ mid ] > num:
            recursion_bin_search( arr[ left_ind : mid - 1 ], num )
        else:
            return mid

    return -1



if __name__ == '__main__':
    arr = [1, 2, 3, 4, 5, 6, 7, 8, 9]
    x =  4
    idx = cicle_bin_search(arr, x)
    print( f'Индекс: { idx }, элемент: { x }' )

"""Задание 2 (Cортировка вставкой)"""

import copy



def insertion_index_by_bin_search( arr: list, num: int, reverse: bool = False ) -> int:

    left_ind, right_ind = 0, len( arr ) - 1

    while left_ind <= right_ind:
        mid = ( left_ind + right_ind ) // 2

        if reverse:
            if arr[mid] > num:
                left_ind = mid + 1
            else:
                right_ind = mid - 1
        else:
            if arr[ mid ] < num:
                left_ind = mid + 1
            else:
                right_ind = mid - 1

    return left_ind


def insertion_sort( arr: list, reverse: bool = False ) -> list:

    arr = copy.deepcopy( arr )

    for i in range( 1, len( arr ) ):
        insert_index = insertion_index_by_bin_search( arr[:i], arr[ i ], reverse )
        insert_num = arr[ i ]
        for j in range(i, insert_index, -1):
            arr[ j ] = arr[ j - 1]
        arr[ insert_index ] = insert_num

    return arr



if __name__ == "__main__":

    print("=== ТЕСТ СОРТИРОВКИ ГОВНА ===\n")

    tests = [
        ([], []),
        ([1], [1]),
        ([2, 1], [1, 2]),
        ([3, 2, 1], [1, 2, 3]),
        ([1, 3, 2], [1, 2, 3]),
        ([2, 2, 1], [1, 2, 2]),
        ([5, 1, 4, 2, 3], [1, 2, 3, 4, 5]),
        ([-1, -3, 0, 2], [-3, -1, 0, 2]),
    ]

    passed = 0
    for i, (input_arr, expected) in enumerate(tests, 1):

        test_arr = input_arr.copy()
        result = insertion_sort(test_arr)

        if result == expected:
            print(f"+ Тест {i}: {input_arr} -> {result}")
            passed += 1
        else:
            print(f"- Тест {i}: {input_arr} -> {result} (ожидалось {expected})")

    print(f"\nРезультат: {passed}/{len(tests)} тестов пройдено")

"""Задание 3 ('Е' баллы студентов)"""

def sort_by_key( arr: list, key_idx: int, reverse: bool = False ) -> list:

    arr = arr[:]
    n = len( arr )

    for i in range( 1, n ):
        cur = arr[ i ]
        j = i - 1

        while j >= 0:
            cur_key = cur[ key_idx ]
            prev_key = arr[ j ][ key_idx ]

            if reverse:
                move = cur_key > prev_key
            else:
                move = cur_key < prev_key

            if move:
                arr[ j + 1 ] = arr[ j ]
                j -= 1
            else:
                break

        arr[ j + 1 ] = cur

    return arr



def multi_key_sort( arr: list, key1, key2, key3, rev1=False, rev2=False, rev3=False ) -> list:

    res = arr[:]

    res = sort_by_key( res, key3, rev3 )
    res = sort_by_key( res, key2, rev2 )
    res = sort_by_key( res, key1, rev1 )

    return res



def search_by_subj_and_grade( arr: list, subject: str, grade: int ) -> list:

    res = []

    for name, subj, grd in arr:
        if subj== subject and grd == grade:
            res.append( (name, subj, grd) )

    return res



def avg_grade_per_subj( arr: list ) -> dict:

    subjects = {}

    for _, subj, grade in arr:
        if not subj in subjects:
            subjects[ subj ] = [ 0, 0 ]
        subjects[ subj ][ 0 ] += grade
        subjects[ subj ][ 1 ] += 1

    avgs = {}

    for subj, ( total, count ) in subjects.items():
        avg = total / count
        avgs[ subj ] = avg

    return avgs



def best_students_per_subject( arr: list):

    student_subject_grades = {}

    for name, subject, grade in arr:
        if name not in student_subject_grades:
            student_subject_grades[ name ] = [ 0, 0 ]
        student_subject_grades[ name ][ 0 ] += grade
        student_subject_grades[ name ][ 1 ] += 1

    best_by_subject = {}

    for name, ( total, count )in student_subject_grades.items():
        avg = total / count
        best_by_subject[ name ] = avg

    return best_by_subject



if __name__ == '__main__':

    students = [
    ( "Анна", "Математика", 85 ),
    ( "Борис", "Физика", 90 ),
    ( "Анна", "Физика", 95 ),
    ( "Борис", "Математика", 80 ),
    ( "Вера", "Математика", 90 ),
    ]

    print( "Отсортированные данные:" )
    sorted_data = multi_key_sort( students, 1, 2, 0, rev2 = True )
    for s in sorted_data:
        print( s )

    print( "\nПоиск студентов с оценкой 90 по Математике:" )
    print( search_by_subj_and_grade( students, "Математика", 90 ) )

    print( "\nСредние оценки по предметам:" )
    print( avg_grade_per_subj( students ) )

    print( "\nЛучшие студенты по предметам:" )
    print( best_students_per_subject( students ) )