# -*- coding: utf-8 -*-
"""lab1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wqO4vr0CWMnnAHxM7bMT3GB8Xqltz4Lk
"""

st = input('Введите строку:').split()

ans = {}
for word in st:
    ans[word] = st.count(word)
print(f'Количество слов: {len(st)}')
print(f'Слова в алфвитном порядке: {sorted(st)}')
print(f'Уникальные слова: {list(set(st))}')
print('Частота слов:')
for key in ans.keys():
    print(f'{key}: {ans[key]}')

nums = list(map(int, input('Введите числа через пробел:').split()))

ch = 0
nech = 0

for num in nums:
    if num % 2 == 0:
        ch += 1
    else:
        nech += 1

print('Анализ чисел:')
print(f'Максимальное число: {max(nums)}')
print(f'Минимальное число: {min(nums)}')
print(f'Среднее арифметическое: {round(sum(nums)/len(nums), 2)}')
print(f'Количесто чётных чисел: {ch}')
print(f'Количество нечётных чисел: {nech}')

import sys

a = int(input('Введите число А: '))
b = int(input('Введите число В: '))

if a > b:
    sys.exit('А должно быть больше В')

resheto = [True]*(b+1)
resheto[0] = resheto[1] = False

for i in range(2, int(b**0.5)+1):
    if resheto[i]:
        start = max(i*i, ((a+i-1)//i)*i)
        for j in range(start, b+1, i):
            resheto[j] = False

primes = [i for i in range(a, b+1) if resheto[i]]
print(f'Простые числа в диапазоне [{a}, {b}]: {primes}')
print(f'Количество простых чисел: {len(primes)}')