# -*- coding: utf-8 -*-
"""Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lehZqioq0pYa6qt0Rbx_TRJ44KoLKRp5

ЗАДАНИЕ 1

Связный список
"""

class Node:
    def __init__(self, data = None):
        self.data = data
        self.next = None



class LinkedList:
    def __init__(self, capacity):
        self.head = None
        self.capacity = capacity
        self.size = 0

    def contain(self, data):
        LastNode = self.head
        cnt = 0
        while LastNode:
            if LastNode.data == data:
                return True
            else:
                LastNode = LastNode.next
        return False

    def add_to_start(self, data):
        if self.size + 1 == self.capacity:
            return
        new = Node(data)
        if self.head is None:
            self.head = new
            return
        new.next = self.head
        self.head = new
        self.size += 1
        return

    def add_to_end(self, data):
        if self.size + 1 == self.capacity:
            return
        new = Node(data)
        if self.head is None:
            self.head = new
            return
        cur = self.head
        while cur.next:
            cur = cur.next
        cur.next = new
        self.size += 1
        return

    def rm_from_start(self):
        if self.head is None:
            print('Список пуст')
            return
        start_node = self.head
        self.head = start_node.next
        start_node.next = None
        self.size -= 1
        return

    def rm_from_end(self):
        if self.head is None:
            print('Список пуст')
            return
        if self.head.next is None:
            self.head = None
            return
        prelast = self.head
        while prelast.next.next:
            prelast = prelast.next
        prelast.next = None
        self.size -= 1
        return

    def rm_node_etot(self, node):
        if self.head is None:
            print('Список пуст')
            return
        cur = self.head
        while cur.next.data != node.data:
            cur = cur.next
        cur.next = node.next
        node.next = None
        self.size -= 1
        return

    def rm_node(self, idx):
        if self.head is None:
            print('Список пуст')
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next is None:
                print(f'Индекса {idx} нет')
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = cur.next.next
        ncur.next = None
        self.size -= 1
        return

    def add_node(self, idx, node):
        if self.size + 1 == self.capacity:
            return
        if self.head is None:
            self.head = node
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next is None:
                cur.next = node
                node.next = None
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = node
        node.next = ncur
        self.size += 1
        return

    def out(self):
        cur = self.head
        while cur != None:
            print(cur.data, end = ' --> ')
            cur = cur.next
        print('None')
        return

lst = LinkedList(5)

for i in range(1, 10):
    lst.add_to_end(i)

lst.out()

print(lst.contain(6))

lst.add_to_start(99)
lst.out()

lst.rm_from_start()
lst.out()

lst.rm_from_end()
lst.out()

lst.rm_node(2)
lst.out()

lst.add_node(2, Node(3))
lst.out()

lst.add_to_end(9)
lst.out()

"""Двусвязный список"""

class Node:
    def __init__(self, data = None):
        self.data = data
        self.next = None
        self.prev = None



class DoubleLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def contain(self, data):
        cur = self.head
        while cur:
            if cur.data == data:
                return True
            else:
                cur = cur.next

    def add_to_start(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            return
        new.next = self.head
        self.head = new
        new.next.prev = self.head
        return

    def add_to_end(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            self.tail = new
            return
        new.prev = self.tail
        self.tail = new
        new.prev.next = self.tail
        return

    def rm_from_start(self):
        if self.head is None:
            print('Список пуст')
            return
        start_node = self.head
        self.head = start_node.next
        start_node.next = None
        self.head.prev = None
        return

    def rm_from_end(self):
        if self.head is None:
            print('Список пуст')
            return
        if self.head.next is None:
            self.head = None
            return
        cur = self.tail
        self.tail = cur.prev
        self.tail.next = None
        cur.prev = None
        return

    def rm_node_etot(self, node):
        if self.head is None:
            print('Список пуст')
            return
        cur = self.head
        while cur.next.data != node.data:
            cur = cur.next
        cur.next = node.next
        node.next = None
        node.prev = None
        return

    def rm_node(self, idx):
        if self.head is None:
            print('Список пуст')
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next is None:
                print(f'Индекса {idx} нет')
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = cur.next.next
        ncur.next = None
        ncur.prev = None
        return

    def add_node(self, idx, node):
        if self.head is None:
            self.head = node
            self.tail = node
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next is None:
                cur.next = node
                node.next = None
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = node
        node.next = ncur
        return

    def out(self):
        cur = self.head
        print("None", end = ' <-> ')
        while cur != None:
            print(cur.data, end = ' <-> ')
            cur = cur.next
        print('None')
        return

lst = DoubleLinkedList()

for i in range(1, 10):
    lst.add_to_end(i)

lst.out()

lst.add_to_start(99)
lst.out()

lst.rm_from_start()
lst.out()

lst.rm_from_end()
lst.out()

lst.rm_node(2)
lst.out()

lst.add_node(2, Node(3))
lst.out()

lst.add_to_end(9)
lst.out()

lst.rm_node_etot(Node(9))
lst.out()

"""Односвязный циклический список"""

class Node:
    def __init__(self, data = None):
        self.data = data
        self.next = None



class LinkedList:
    def __init__(self):
        self.head = None

    def contain(self, data):
        LastNode = self.head
        while LastNode:
            if LastNode.data == data:
                return True
            else:
                LastNode = LastNode.next

    def add_to_start(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            self.head.next = self.head
            return
        curp = self.head
        new.next = self.head
        self.head = new
        cur = self.head.next
        while cur.next != curp:
            cur = cur.next
        cur.next = self.head
        return

    def add_to_end(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            self.head.next = self.head
            return
        cur = self.head
        while cur.next != self.head:
            cur = cur.next
        cur.next = new
        new.next = self.head
        return

    def rm_from_start(self):
        if self.head is None:
            print('Список пуст')
            return
        start_node = self.head
        self.head = start_node.next
        start_node.next = None
        cur = self.head
        while cur.next != start_node:
            cur = cur.next
        cur.next = self.head
        start_node.next = None
        return

    def rm_from_end(self):
        if self.head is None:
            print('Список пуст')
            return
        if self.head.next is self.head:
            self.head = None
            return
        prelast = self.head
        while prelast.next.next != self.head:
            prelast = prelast.next
        prelast.next.next = None
        prelast.next = self.head
        return

    def rm_node_etot(self, node):
        if self.head is None:
            print('Список пуст')
            return
        cur = self.head
        while cur.next != self.head:
            cur = cur.next
        cur.next = node.next
        node.next = None
        return

    def rm_node(self, idx):
        if self.head is None:
            print('Список пуст')
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next == self.head:
                print(f'Индекса {idx} нет')
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = cur.next.next
        ncur.next = None
        return

    def add_node(self, idx, node):
        if self.head is None:
            self.head = node
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next == self.head:
                cur.next = node
                node.next = self.head
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = node
        node.next = ncur
        return

    def out(self):
        cur = self.head.next
        print(self.head.data, end = ' --> ')
        while cur != self.head:
            print(cur.data, end = ' --> ')
            cur = cur.next
        print(f'{self.head.data}')
        return

lst = LinkedList()

for i in range(1, 10):
    lst.add_to_end(i)

lst.out()

lst.add_to_start(99)
lst.out()

lst.rm_from_start()
lst.out()

lst.rm_from_end()
lst.out()

lst.rm_node(2)
lst.out()

lst.add_node(2, Node(3))
lst.out()

lst.add_to_end(9)
lst.out()

"""Циклический двусвязный список"""

class Node:
    def __init__(self, data = None):
        self.data = data
        self.next = None
        self.prev = None



class DoubleLinkedList:
    def __init__(self):
        self.head = None
        self.tail = None

    def contain(self, data):
        cur = self.head
        while cur:
            if cur.data == data:
                return True
            else:
                cur = cur.next

    def add_to_start(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            self.head.next = self.head
            self.head.prev = self.head
            return
        new.next = self.head
        self.head = new
        self.head.prev = self.tail
        new.next.prev = self.head
        self.tail.next = self.head
        return

    def add_to_end(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            self.head.next = new
            self.head.prev = new
            self.tail = new
            self.tail.next = new
            self.tail.prev = new
            return
        new.prev = self.tail
        self.tail = new
        new.prev.next = self.tail
        self.tail.next = self.head
        return

    def rm_from_start(self):
        if self.head is None:
            print('Список пуст')
            return
        start_node = self.head
        self.head = start_node.next
        start_node.next = None
        self.head.prev = self.tail
        cur = self.head
        while cur.next != start_node:
            cur = cur.next
        cur.next = self.head
        start_node.next = None
        return

    def rm_from_end(self):
        if self.head is None:
            print('Список пуст')
            return
        if self.head.next is None:
            self.head = None
            return
        cur = self.tail
        self.tail = cur.prev
        self.tail.next = self.head
        cur.prev = None
        cur.next = None
        return

    def rm_node_etot(self, node):
        if self.head is None:
            print('Список пуст')
            return
        cur = self.head
        if cur.data == node.data:
            self.rm_from_start()
            return
        while cur.next != self.head:
            if cur.next.data == node.data:
                denode = cur.next
                if denode == self.tail:
                    self.rm_from_end()
                    return
                else:
                    cur.next = denode.next
                    denode.prev = cur
                denode.next = None
                denode.prev = None
                return
            cur = cur.next
        return

    def rm_node(self, idx):
        if self.head is None:
            print('Список пуст')
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next == self.head:
                print(f'Индекса {idx} нет')
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = cur.next.next
        ncur.next = None
        ncur.prev = None
        return

    def add_node(self, idx, node):
        if self.head is None:
            self.head = node
            self.tail = node
            self.head.next = node
            self.head.prev = node
            self.tail.next = node
            self.tail.prev = node
            return
        cur_idx = 0
        cur = self.head
        while cur_idx + 1 != idx:
            if cur.next is self.head:
                cur.next = node
                node.next = self.head
                node.prev = cur
                self.tail = node
                return
            cur = cur.next
            cur_idx += 1
        ncur = cur.next
        cur.next = node
        ncur.prev = node
        node.prev = cur
        node.next = ncur
        return

    def out(self):
        cur = self.head.next
        print(f"{self.tail.data}", end = ' <-> ')
        print(f"{self.head.data}", end = ' <-> ')
        while cur != self.head:
            print(cur.data, end = ' <-> ')
            cur = cur.next
        print(f'{self.head.data}')
        return

lst = DoubleLinkedList()

for i in range(1, 10):
    lst.add_to_end(i)

lst.out()

lst.add_to_start(99)
lst.out()

lst.rm_from_start()
lst.out()

lst.rm_from_end()
lst.out()

lst.rm_node(2)
lst.out()

lst.add_node(2, Node(3))
lst.out()

lst.add_to_end(9)
lst.out()

lst.rm_node_etot(Node(3))
lst.out()

"""ЗАДАНИЕ 2"""

class Node:
    def __init__(self, data = None):
        self.data = data
        self.next = None



class LinkedList:
    def __init__(self):
        self.head = None

    def add_to_end(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            return
        cur = self.head
        while cur.next:
            cur = cur.next
        cur.next = new
        return

    def out(self, cur):
        while cur != None:
            print(cur.data, end = ' --> ')
            cur = cur.next
        print('None')
        return



def reverse(head, k):

    if not head or k <= 1:
        return head

    cnt = 0
    cur = head
    while cur and cnt < k:
        cur = cur.next
        cnt += 1

    if cnt < k:
        return head

    prev = None
    cur = head
    for _ in range(k):
        next = cur.next
        cur.next = prev
        prev = cur
        cur = next

    head.next = reverse(cur, k)

    return prev


k = 3
lst = LinkedList()

for i in [1,2,3,5,6,7,8]:
    lst.add_to_end(i)
lst.out(lst.head)

head = reverse(lst.head, k)
lst.out(head)

"""ЗАДАНИЕ №3"""

class Node:
    def __init__(self, data = None):
        self.data = data
        self.next = None



class LinkedList:
    def __init__(self):
        self.head = None

    def add_to_end(self, data):
        new = Node(data)
        if self.head is None:
            self.head = new
            return
        cur = self.head
        while cur.next:
            cur = cur.next
        cur.next = new
        return

    def out(self, cur):
        while cur != None:
            print(cur.data, end = ' --> ')
            cur = cur.next
        print('None')
        return



def polindrom(lst):
    snode = lst.head
    fnode = lst.head
    mid = None
    cur = lst.head
    ncur = None
    prev = None
    cnt = 0

    while fnode:
        snode = snode.next
        cnt += 1
        if fnode and fnode.next:
            fnode = fnode.next.next
        else:
            fnode = None

    ncur = snode

    while ncur:
        next = ncur.next
        ncur.next = prev
        prev = ncur
        ncur = next

    while cur and prev:
        if cur.data != prev.data:
            return False
        cur = cur.next
        prev = prev.next

    return True



lst = LinkedList()

for i in [1,2,3,3,2,1]:
    lst.add_to_end(i)
lst.out(lst.head)

print(polindrom(lst))