# -*- coding: utf-8 -*-
"""lab5_hashmap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Df5KCBulfjD4kw62W5z56I9eWWzuchI
"""

import time
import matplotlib.pyplot as plt
import numpy as np
from typing import Any
from functools import wraps



class Node:

    __slots__ = ('key', 'data', 'next')

    def __init__(self, key, data = None):
        self.key = key
        self.data = data
        self.next = None



class LinkedList:

    def __init__(self):
        self.head = None


    def add_to_start(self, key, data):

        cur = self.head
        while cur is not None:
            if cur.key == key:
                cur.data = data
                return True
            cur = cur.next

        new = Node(key, data)
        if self.head is None:
            self.head = new
            return False
        new.next = self.head
        self.head = new

        return False


    def rm_node_etot(self, key):

        if self.head is None:
            return False
        if self.head.key == key:
            self.head = self.head.next
            return True
        cur = self.head
        while cur.next is not None:
            if cur.next.key == key:
                cur.next = cur.next.next
                return True
            cur = cur.next

        return False



#======================================================================#



class HashMapTimer:

    timings = {
        'setitem': [],
        'getitem': [],
        'delitem': []
    }


    @staticmethod
    def time_counter(method_name):
        def decorator(func):
            @wraps(func)
            def wrapper(self, *args, **kwargs):

                current_ff = self._check_filling_factor()

                start = time.perf_counter()
                result = func(self, *args, **kwargs)
                duration = time.perf_counter() - start

                HashMapTimer.timings[method_name].append((current_ff, duration))

                return result
            return wrapper
        return decorator



#======================================================================#



class Hash_map:

    def __init__(self, table_size, filling_factor = 0.7):
        self.__table_size = table_size
        self.__table = [None] * table_size
        self.__filling_factor = filling_factor
        self.__count = 0


    @staticmethod
    def __hash(key: Any) -> int:

        if isinstance(key, str):
            return sum(ord(c) for c in str(key))

        return hash(key)


    def _get_index(self, key: Any) -> int:
        return Hash_map.__hash(key) % self.__table_size


    def _check_filling_factor(self) -> float:
        ff = self.__count / self.__table_size
        return ff


    @HashMapTimer.time_counter('setitem')
    def __setitem__(self, key: Any, value: Any):

        idx = self._get_index(key)

        if self.__table[idx] is None:
            self.__table[idx] = (key, value)
            self.__count += 1
        elif isinstance(self.__table[idx], tuple):
            tmp = self.__table[idx]
            self.__table[idx] = LinkedList()
            self.__table[idx].add_to_start(tmp[0], tmp[1])
            self.__table[idx].add_to_start(key, value)
            self.__count += 1
        elif isinstance(self.__table[idx], LinkedList):
            was_updated = self.__table[idx].add_to_start(key, value)
            if not was_updated:
                self.__count += 1

        self._check_resize()

        return


    @HashMapTimer.time_counter('getitem')
    def __getitem__(self, key: Any) -> Any:

        idx = self._get_index(key)
        bucket = self.__table[idx]

        if isinstance(bucket, tuple):
            if bucket[0] == key:
                return bucket[1]
        elif isinstance(bucket, LinkedList):
            cur = bucket.head
            while cur is not None:
                if cur.key == key:
                    return cur.data
                cur = cur.next

        raise KeyError(key)


    def get(self, key: Any, default = None):
        try:
            return self[key]
        except KeyError:
            return default


    @HashMapTimer.time_counter('delitem')
    def __delitem__(self, key):

        idx = self._get_index(key)
        bucket = self.__table[idx]

        if isinstance(bucket, tuple):
            self.__table[idx] = None
            self.__count -= 1
            return
        elif isinstance(bucket, LinkedList):
            if bucket.rm_node_etot(key):
                self.__count -= 1
                if bucket.head is None:
                    self.__table[idx] = None
                return

        raise KeyError(key)


    def __contains__(self, key):
        try:
            self[key]
            return True
        except KeyError:
            return False


    def _check_resize(self):
        if self._check_filling_factor() >= self.__filling_factor:
            self._resize()
            return

    def items(self):

        for bucket in self.__table:
            if bucket is None:
                continue

            if isinstance(bucket, tuple):
                yield bucket
            else:
                cur = bucket.head
                while cur:
                    yield (cur.key, cur.data)
                    cur = cur.next


    def _resize(self):
        new_table_size = self.__table_size * 2
        new_table = Hash_map(new_table_size)

        for key, value in self.items():
            new_table[key] = value

        self.__table = new_table.__table
        self.__table_size = new_table_size


    @property
    def table_size(self):
        return self.__table_size


    @property
    def count(self):
        return self.__count


    @property
    def filling_factor(self):
        return self.__filling_factor







def plot_simple_timings(num_operations=500, table_size=50):

    HashMapTimer.timings = {
        'setitem': [],
        'getitem': [],
        'delitem': []
    }

    hm = Hash_map(table_size=table_size, filling_factor=0.7)

    print(f"Заполняем таблицу {num_operations} элементами...")

    for i in range(num_operations):
        hm[f"key_{i}"] = f"value_{i}"

    print("Читаем элементы...")
    for i in range(num_operations):
        try:
            _ = hm[f"key_{i}"]
        except KeyError:
            pass

    print("Удаляем элементы...")
    for i in range(num_operations):
        try:
            del hm[f"key_{i}"]
        except KeyError:
            pass

    timings = HashMapTimer.timings

    fig, axes = plt.subplots(2, 2, figsize=(12, 8))

    # 1. График добавления
    ax1 = axes[0, 0]
    ff_set = [item[0] for item in timings['setitem']]
    time_set = [item[1] * 1_000_000 for item in timings['setitem']]
    ax1.scatter(ff_set, time_set, s=5, alpha=0.5, color='blue')
    ax1.set_xlabel('Заполненность таблицы')
    ax1.set_ylabel('Время (мкс)')
    ax1.set_title('Добавление элементов (setitem)')
    ax1.grid(True, alpha=0.3)
    ax1.axvline(x=hm.filling_factor, color='red', linestyle='--', alpha=0.7)
    ax1.set_yscale('log')

    # 2. График чтения
    ax2 = axes[0, 1]
    ff_get = [item[0] for item in timings['getitem']]
    time_get = [item[1] * 1_000_000 for item in timings['getitem']]
    ax2.scatter(ff_get, time_get, s=5, alpha=0.5, color='green')
    ax2.set_xlabel('Заполненность таблицы')
    ax2.set_ylabel('Время (мкс)')
    ax2.set_title('Чтение элементов (getitem)')
    ax2.grid(True, alpha=0.3)
    ax2.axvline(x=hm.filling_factor, color='red', linestyle='--', alpha=0.7)
    ax2.set_yscale('log')

    # 3. График удаления
    ax3 = axes[1, 0]
    ff_del = [item[0] for item in timings['delitem']]
    time_del = [item[1] * 1_000_000 for item in timings['delitem']]
    ax3.scatter(ff_del, time_del, s=5, alpha=0.5, color='red')
    ax3.set_xlabel('Заполненность таблицы')
    ax3.set_ylabel('Время (мкс)')
    ax3.set_title('Удаление элементов (delitem)')
    ax3.grid(True, alpha=0.3)
    ax3.axvline(x=hm.filling_factor, color='red', linestyle='--', alpha=0.7)
    ax3.set_yscale('log')

    # 4. Все три на одном графике
    ax4 = axes[1, 1]
    ax4.scatter(ff_set, time_set, s=5, alpha=0.5, color='blue', label='Добавление')
    ax4.scatter(ff_get, time_get, s=5, alpha=0.5, color='green', label='Чтение')
    ax4.scatter(ff_del, time_del, s=5, alpha=0.5, color='red', label='Удаление')
    ax4.set_xlabel('Заполненность таблицы')
    ax4.set_ylabel('Время (мкс)')
    ax4.set_title('Сравнение всех операций')
    ax4.legend()
    ax4.grid(True, alpha=0.3)
    ax4.axvline(x=hm.filling_factor, color='red', linestyle='--', alpha=0.7)
    ax4.set_yscale('log')

    plt.suptitle(f'Производительность хеш-таблицы (размер={table_size})', fontsize=14)
    plt.tight_layout()
    plt.show()

    # Выводим средние значения
    print("\n" + "="*50)
    print("СРЕДНЕЕ ВРЕМЯ ВЫПОЛНЕНИЯ:")
    print("="*50)
    print(f"Добавление: {np.mean(time_set):.4f} мкс")
    print(f"Чтение:     {np.mean(time_get):.4f} мкс")
    print(f"Удаление:   {np.mean(time_del):.4f} мкс")
    print(f"\nКрасная линия на графике - порог заполненности ({hm.filling_factor})")



if __name__ == "__main__":

    plot_simple_timings(num_operations=500, table_size=50)

    plot_simple_timings(num_operations=5000, table_size=50)