# -*- coding: utf-8 -*-
"""Lab7_sorts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w9dyMJJvBQPMyOOSERzTVeHsa-9BZfMi

Задание 1
"""

from typing import Any



class Node:
    def __init__( self, data = None ):
        self.data = data
        self.next = None



class LinkedList:

    def __init__( self ):
        self.head = None
        self.__length = 0


    def __len__( self ) -> int:

        return self.__length


    def __getitem__( self, key: int ) :

        if isinstance( key, slice ):
            if key.step is not None and key.step != 1:
                raise ValueError( "Slice step must be 1" )

            start, stop = key.start, key.stop

            length = len( self )

            if start is None:
                start = 0
            elif start < 0:
                start = length + start
                if start < 0:
                    start = 0

            if stop is None:
                stop = length
            elif stop < 0:
                stop = length + stop
                if stop < 0:
                    stop = 0

            if start >= length or stop <= start:
                return LinkedList()

            if stop > length:
                stop = length

            result = LinkedList()

            current = self.head
            for _ in range( start ):
                if current is None:
                    return result
                current = current.next

            for _ in range( start, stop ):
                if current is None:
                    break
                result.add_to_end( current.data )
                current = current.next

            return result

        elif isinstance( key, int ):
            if key < 0:
                key = len( self ) + key
            if key < 0 or key >= len( self ):
                raise IndexError( "Index out of range" )

            current = self.head
            for _ in range( key ):
                current = current.next
            return current.data


    def contain( self, data: Any ) -> None:

        LastNode = self.head

        while LastNode:
            if LastNode.data == data:
                return True
            else:
                LastNode = LastNode.next

        return False


    def add_to_start( self, data: Any ) -> None:

        new = Node( data )

        if self.head is None:
            self.head = new
            self.__length += 1
            return

        new.next = self.head
        self.head = new
        self.__length += 1

        return


    def add_to_end (self, data: Any ) -> None:

        new = Node( data )
        if self.head is None:
            self.head = new
            self.__length += 1
            return

        cur = self.head

        while cur.next:
            cur = cur.next

        cur.next = new
        self.__length += 1

        return


    def rm_from_start( self ) -> None:

        if self.head is None:
            print( 'Список пуст' )
            return

        start_node = self.head
        self.head = start_node.next
        start_node.next = None
        self.__length -= 1

        return


    def rm_from_end( self ) -> None:

        if self.head is None:
            print( 'Список пуст' )
            return

        if self.head.next is None:
            self.head = None
            self.__length -= 1
            return

        prelast = self.head

        while prelast.next.next:
            prelast = prelast.next

        prelast.next = None
        self.__length -= 1

        return


    def rm_node_etot( self, node: Node ) -> None:

        if self.head is None:
            print( 'Список пуст' )
            return

        cur = self.head

        while cur.next.data != node.data:
            cur = cur.next

        cur.next = node.next
        node.next = None
        self.__length -= 1

        return


    def rm_node( self, idx: int ) -> None:

        if self.head is None:
            print( 'Список пуст' )
            return

        cur_idx = 0
        cur = self.head

        while cur_idx + 1 != idx:
            if cur.next is None:
                print( f'Индекса {idx} нет' )
                return
            cur = cur.next
            cur_idx += 1

        ncur = cur.next
        cur.next = cur.next.next
        ncur.next = None
        self.__length -= 1

        return


    def add_node( self, idx, node ) -> None:

        if self.head is None:
            self.head = node
            return

        cur_idx = 0
        cur = self.head

        while cur_idx + 1 != idx:
            if cur.next is None:
                cur.next = node
                node.next = None
                return
            cur = cur.next
            cur_idx += 1

        ncur = cur.next
        cur.next = node
        node.next = ncur
        self.__length += 1

        return


    def out( self ) -> None:
        cur = self.head
        while cur != None:
            print( cur.data, end = ' --> ' )
            cur = cur.next
        print( 'None' )
        return



#==========================================================#



def linked_merge_sort( lst: LinkedList ) -> LinkedList:

    if len(lst) <= 1:
        return lst

    mid = len(lst) // 2
    left = linked_merge_sort(lst[:mid])
    right = linked_merge_sort(lst[mid:])

    return merge(left, right)


def merge(left: LinkedList, right: LinkedList) -> LinkedList:

    result = LinkedList()
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] < right[j]:
            result.add_to_end(left[i])
            i += 1
        else:
            result.add_to_end(right[j])
            j += 1

    while i < len(left):
        result.add_to_end(left[i])
        i += 1

    while j < len(right):
        result.add_to_end(right[j])
        j += 1

    return result



if __name__ == '__main__':

    lst = LinkedList()

    for i in range(10):
        if i%2 == 0:
            lst.add_to_start(i)
        else:
            lst.add_to_end(i)

    lst.out()
    sorted_lst = linked_merge_sort(lst)
    print("Отсортированный массив:")
    sorted_lst.out()

"""Задание 2"""

import time
import random
import sys
from typing import List, Callable, Tuple
from functools import wraps

sys.setrecursionlimit(10**6)



def timer_decorator(func_name: str = None):

    def decorator(func: Callable) -> Callable:

        @wraps(func)
        def wrapper(*args, **kwargs):

            start = time.perf_counter()
            result = func(*args, **kwargs)
            end = time.perf_counter()
            elapsed_ms = (end - start) * 1000
            name = func_name if func_name else func.__name__

            return result, elapsed_ms, name

        return wrapper

    return decorator



def merge(left: List[int], right: List[int]) -> List[int]:

    result = []
    i = j = 0

    while i < len(left) and j < len(right):
        if left[i] <= right[j]:
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])

    return result


@timer_decorator("Слияние (стандарт)")
def merge_sort_standard(arr: List[int]) -> List[int]:

    if len(arr) <= 1:
        return arr
    mid = len(arr) // 2
    left = merge_sort_standard(arr[:mid])[0]
    right = merge_sort_standard(arr[mid:])[0]

    return merge(left, right)


@timer_decorator("Быстрая (стандарт)")
def quick_sort_standard(arr: List[int]) -> List[int]:

    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]

    return quick_sort_standard(left)[0] + middle + quick_sort_standard(right)[0]


@timer_decorator("Python sorted()")
def builtin_sort(arr: List[int]) -> List[int]:
    return sorted(arr)



def merge_optimized(arr: List[int], temp: List[int], left: int, mid: int, right: int) -> None:

    i, j, k = left, mid + 1, left
    while i <= mid and j <= right:
        if arr[i] <= arr[j]:
            temp[k] = arr[i]
            i += 1
        else:
            temp[k] = arr[j]
            j += 1
        k += 1
    while i <= mid:
        temp[k] = arr[i]
        i += 1
        k += 1
    while j <= right:
        temp[k] = arr[j]
        j += 1
        k += 1
    for i in range(left, right + 1):
        arr[i] = temp[i]


def merge_sort_optimized_internal(arr: List[int], temp: List[int], left: int, right: int) -> None:

    if left >= right:
        return
    mid = (left + right) // 2
    merge_sort_optimized_internal(arr, temp, left, mid)
    merge_sort_optimized_internal(arr, temp, mid + 1, right)
    merge_optimized(arr, temp, left, mid, right)


@timer_decorator("Слияние (оптимизир.)")
def merge_sort_optimized(arr: List[int]) -> List[int]:

    arr_copy = arr.copy()
    temp = [0] * len(arr_copy)
    merge_sort_optimized_internal(arr_copy, temp, 0, len(arr_copy) - 1)
    return arr_copy


def quick_sort_optimized_internal(arr: List[int], low: int, high: int) -> None:

    if low >= high:
        return

    if high - low < 20:
        insertion_sort(arr, low, high)
        return

    mid = (low + high) // 2
    if arr[low] > arr[mid]:
        arr[low], arr[mid] = arr[mid], arr[low]
    if arr[low] > arr[high]:
        arr[low], arr[high] = arr[high], arr[low]
    if arr[mid] > arr[high]:
        arr[mid], arr[high] = arr[high], arr[mid]

    pivot = arr[mid]
    arr[mid], arr[high] = arr[high], arr[mid]

    i = low - 1
    for j in range(low, high):
        if arr[j] <= pivot:
            i += 1
            arr[i], arr[j] = arr[j], arr[i]

    arr[i + 1], arr[high] = arr[high], arr[i + 1]
    pivot_index = i + 1

    quick_sort_optimized_internal(arr, low, pivot_index - 1)
    quick_sort_optimized_internal(arr, pivot_index + 1, high)


def insertion_sort(arr: List[int], low: int, high: int) -> None:

    for i in range(low + 1, high + 1):
        key = arr[i]
        j = i - 1
        while j >= low and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key


@timer_decorator("Быстрая (оптимизир.)")
def quick_sort_optimized(arr: List[int]) -> List[int]:

    arr_copy = arr.copy()
    quick_sort_optimized_internal(arr_copy, 0, len(arr_copy) - 1)

    return arr_copy



def run_tests(sizes: List[int]) -> None:

    sort_functions = [
        merge_sort_standard,
        quick_sort_standard,
        builtin_sort,
        merge_sort_optimized,
        quick_sort_optimized
    ]

    for size in sizes:
        print(f"\n{'='*60}")
        print(f"Размер массива: {size}")
        print('-' * 60)
        print(f"{'Метод':<35} | {'Время (мс)':>10}")
        print('-' * 60)

        original_arr = [random.randint(0, size) for _ in range(size)]

        results = {}
        for sort_func in sort_functions:
            result, elapsed_ms, name = sort_func(original_arr.copy())
            results[name] = elapsed_ms
            print(f"{name:<35} | {elapsed_ms:>10.2f}")

        print('-' * 60)

        if "Слияние (стандарт)" in results and "Слияние (оптимизир.)" in results:
            speedup = results["Слияние (стандарт)"] / results["Слияние (оптимизир.)"]
            print(f"Слияние (оптимизир.) быстрее стандартной в {speedup:.2f}x")

        if "Быстрая (стандарт)" in results and "Быстрая (оптимизир.)" in results:
            speedup = results["Быстрая (стандарт)"] / results["Быстрая (оптимизир.)"]
            print(f"Быстрая (оптимизир.) быстрее стандартной в {speedup:.2f}x")

        if "Слияние (оптимизир.)" in results and "Быстрая (оптимизир.)" in results:
            if results["Быстрая (оптимизир.)"] < results["Слияние (оптимизир.)"]:
                diff = results["Слияние (оптимизир.)"] - results["Быстрая (оптимизир.)"]
                print(f"Быстрая (оптимизир.) быстрее Слияния (оптимизир.) на {diff:.2f} мс")
            else:
                diff = results["Быстрая (оптимизир.)"] - results["Слияние (оптимизир.)"]
                print(f"Слияние (оптимизир.) быстрее Быстрой (оптимизир.) на {diff:.2f} мс")

        if "Python sorted()" in results and "Слияние (стандарт)" in results:
            speedup = results["Слияние (стандарт)"] / results["Python sorted()"]
            print(f"Python sorted() быстрее стандартного слияния в {speedup:.1f}x")

    print("\n" + "=" * 60)



def main():
    print("="*60)
    print(" " * 15 + "Сравнение алгоритмов сортировки")
    print("="*60)

    sizes = [10**3, 10**4, 10**5, 10**6]
    run_tests(sizes)



if __name__ == "__main__":
    main()

"""Задание 3"""

import random
import sys
sys.setrecursionlimit(100000)

class ComparisonCounter:

    def __init__(self):
        self.count = 0

    def reset(self):
        self.count = 0

    def compare(self, a, b):
        self.count += 1
        return a < b

def natural_merge_sort(arr, counter=None):

    if counter is None:
        counter = ComparisonCounter()

    n = len(arr)
    if n <= 1:
        return arr.copy(), counter.count

    work_arr = arr.copy()
    temp_arr = arr.copy()

    while True:
        runs = []
        i = 0
        while i < n:
            start = i
            i += 1
            while i < n and not counter.compare(work_arr[i], work_arr[i-1]):
                i += 1
            runs.append((start, i))

        if len(runs) <= 1:
            break

        new_runs = []
        for j in range(0, len(runs), 2):
            if j + 1 < len(runs):
                merged_start, merged_end = merge_runs(
                    work_arr, temp_arr,
                    runs[j][0], runs[j][1],
                    runs[j+1][0], runs[j+1][1],
                    counter
                )
                new_runs.append((merged_start, merged_end))
            else:
                new_runs.append(runs[j])

        work_arr, temp_arr = temp_arr, work_arr
        runs = new_runs

        if len(runs) <= 1:
            break

    return work_arr, counter.count

def merge_runs(arr, temp, left1, right1, left2, right2, counter):
    i, j, k = left1, left2, left1

    while i < right1 and j < right2:
        if counter.compare(arr[i], arr[j]):
            temp[k] = arr[i]
            i += 1
        else:
            temp[k] = arr[j]
            j += 1
        k += 1

    while i < right1:
        temp[k] = arr[i]
        i += 1
        k += 1

    while j < right2:
        temp[k] = arr[j]
        j += 1
        k += 1

    return left1, k

def classic_merge_sort(arr, counter=None):
    if counter is None:
        counter = ComparisonCounter()

    if len(arr) <= 1:
        return arr.copy(), counter.count

    mid = len(arr) // 2
    left, _ = classic_merge_sort(arr[:mid], counter)
    right, _ = classic_merge_sort(arr[mid:], counter)

    result = []
    i = j = 0
    while i < len(left) and j < len(right):
        if counter.compare(left[i], right[j]):
            result.append(left[i])
            i += 1
        else:
            result.append(right[j])
            j += 1

    result.extend(left[i:])
    result.extend(right[j:])

    return result, counter.count

def quick_sort(arr, counter=None):
    if counter is None:
        counter = ComparisonCounter()

    if len(arr) <= 1:
        return arr.copy(), counter.count

    first = arr[0]
    middle = arr[len(arr) // 2]
    last = arr[-1]

    if counter.compare(first, middle):
        if counter.compare(middle, last):
            pivot = middle
        else:
            pivot = last if counter.compare(first, last) else first
    else:
        if counter.compare(first, last):
            pivot = first
        else:
            pivot = last if counter.compare(middle, last) else middle

    left = [x for x in arr if counter.compare(x, pivot)]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if counter.compare(pivot, x)]

    left_sorted, _ = quick_sort(left, counter)
    right_sorted, _ = quick_sort(right, counter)

    return left_sorted + middle + right_sorted, counter.count

def generate_arrays(size):

    random_arr = [random.randint(0, size) for _ in range(size)]
    sorted_arr = list(range(size))
    reverse_arr = list(range(size, 0, -1))
    return random_arr, sorted_arr, reverse_arr

def test_sorting_algorithms(sizes):
    results = {
        'size': [],
        'type': [],
        'natural_merge': [],
        'classic_merge': [],
        'quick_sort': []
    }

    for size in sizes:
        print(f"\nРазмер массива: {size}")
        random_arr, sorted_arr, reverse_arr = generate_arrays(size)

        for arr_type, arr in [('Случайный', random_arr),
                               ('Отсортированный', sorted_arr),
                               ('Обратный', reverse_arr)]:

            counter = ComparisonCounter()
            _, natural_comp = natural_merge_sort(arr.copy(), counter)

            counter = ComparisonCounter()
            _, classic_comp = classic_merge_sort(arr.copy(), counter)

            counter = ComparisonCounter()
            _, quick_comp = quick_sort(arr.copy(), counter)

            results['size'].append(size)
            results['type'].append(arr_type)
            results['natural_merge'].append(natural_comp)
            results['classic_merge'].append(classic_comp)
            results['quick_sort'].append(quick_comp)

            print(f"{arr_type:15} | Natural: {natural_comp:8} | Classic: {classic_comp:8} | Quick: {quick_comp:8}")

    return results

def print_table(results, sizes):
    print("\n" + "="*80)
    print("Сводная таблица сравнений:")
    print("="*80)
    print(f"{'Размер':<8} {'Тип':<15} {'Natural Merge':<15} {'Classic Merge':<15} {'Quick Sort':<15}")
    print("-"*80)

    for size in sizes:
        for arr_type in ['Случайный', 'Отсортированный', 'Обратный']:
            idx = results['size'].index(size) if size in results['size'] else -1
            if idx >= 0:
                indices = [i for i in range(len(results['size']))
                          if results['size'][i] == size and results['type'][i] == arr_type]
                if indices:
                    i = indices[0]
                    print(f"{size:<8} {arr_type:<15} {results['natural_merge'][i]:<15} "
                          f"{results['classic_merge'][i]:<15} {results['quick_sort'][i]:<15}")
        print("-"*80)

def analyze_complexity():
    print("\n" + "="*80)
    print("Анализ эффективности алгоритмов:")
    print("="*80)

    sizes = [1000, 2000, 5000, 10000]
    results = test_sorting_algorithms(sizes)
    print_table(results, sizes)


if __name__ == "__main__":
    analyze_complexity()